/*Create Roles*/
CREATE ROLE PA_GERENTE;
GRANT SELECT ON Empleados TO PA_GERENTE;
GRANT SELECT ON Productos TO PA_GERENTE;
GRANT SELECT ON Clientes TO PA_GERENTE;
GRANT SELECT ON Ventas TO PA_GERENTE;

CREATE ROLE PA_ADMINISTRADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON Empleados TO PA_ADMINISTRADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON Productos TO PA_ADMINISTRADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON Clientes TO PA_ADMINISTRADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON Ventas TO PA_ADMINISTRADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON Compras TO PA_ADMINISTRADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON DetallesCompras TO PA_ADMINISTRADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON DetalleSVentas TO PA_ADMINISTRADOR;

CREATE ROLE PA_VENDEDOR;
GRANT SELECT, INSERT, UPDATE ON Personas TO PA_VENDEDOR;
GRANT SELECT, INSERT, UPDATE ON Productos TO PA_VENDEDOR;
GRANT SELECT, INSERT, UPDATE ON Clientes TO PA_VENDEDOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON Ventas TO PA_VENDEDOR;
GRANT SELECT, INSERT, DELETE ON DetalleSVentas TO PA_VENDEDOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON Compras TO PA_VENDEDOR;
GRANT SELECT, INSERT, DELETE ON DetallesCompras TO PA_VENDEDOR;