-- Secuencia de idPersona
CREATE SEQUENCE SEQ_idPersona
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOCYCLE
CACHE 10;

-- Secuencia de idVenta
CREATE SEQUENCE SEQ_idVenta
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOCYCLE
CACHE 10;

-- Secuencia de idDetalleVenta
CREATE SEQUENCE SEQ_idDetalleVenta
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOCYCLE
CACHE 10;



/*XSequence*/
DROP SEQUENCE SEQ_idPersona;
DROP SEQUENCE SEQ_idVenta;
DROP SEQUENCE SEQ_idDetalleVenta;

-- Necestivo volver a iniciar la SEQ_idPersona en 1
ALTER SEQUENCE SEQ_idPersona RESTART WITH 1;