-- Secuencia de idVenta
CREATE SEQUENCE SEQ_idVenta
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOCYCLE
CACHE 10;

-- Secuencia de idDetalleVenta
CREATE SEQUENCE SEQ_idDetalleVenta
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOCYCLE
CACHE 10;

-- Secuencia de idProveedor
CREATE SEQUENCE SEQ_idProveedor
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOCYCLE
CACHE 10;

-- Secuencia de idCompra
CREATE SEQUENCE SEQ_idCompra
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOCYCLE
CACHE 10;

-- Secuencia de idDetalleCompra
CREATE SEQUENCE SEQ_idDetalleCompra
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOCYCLE
CACHE 10;


/*XSequence*/
DROP SEQUENCE SEQ_idVenta;
DROP SEQUENCE SEQ_idDetalleVenta;
DROP SEQUENCE SEQ_idProveedor;
DROP SEQUENCE SEQ_idCompra;
DROP SEQUENCE SEQ_idDetalleCompra;