-- Personas
INSERT INTO Personas (idPersona, nombre, apellidos, identificacion, tipoIdentificacion, dirrecion, correoElectronico)
VALUES (1, 'Juan', 'Perez', '1023456789', 'C.C', 'Calle 1 #2-3', 'juan@gmail.com');
INSERT INTO Personas (idPersona, nombre, apellidos, identificacion, tipoIdentificacion, dirrecion, correoElectronico)
VALUES (2, 'Maria', 'Gomez', '1098765432', 'C.C', 'Calle 2 #4-5', 'maria@gmail.com');
INSERT INTO Personas (idPersona, nombre, apellidos, identificacion, tipoIdentificacion, dirrecion, correoElectronico)
VALUES (3, 'Pedro', 'Lopez', '1045678912', 'C.C', 'Calle 3 #6-7', 'pedro@gmail.com');
INSERT INTO Personas (idPersona, nombre, apellidos, identificacion, tipoIdentificacion, dirrecion, correoElectronico)
VALUES (4, 'Ana', 'Sanchez', '1023159357', 'C.C', 'Calle 4 #8-9', 'ana@gmail.com');
INSERT INTO Personas (idPersona, nombre, apellidos, identificacion, tipoIdentificacion, dirrecion, correoElectronico)
VALUES (5, 'Andres', 'Paez', '1021546879', 'C.C', 'Calle 5 #10-11', 'andres@gmail.com');
INSERT INTO Personas (idPersona, nombre, apellidos, identificacion, tipoIdentificacion, dirrecion, correoElectronico)
VALUES (6, 'Valentina', 'Perez', '831364564', 'C.C', 'Calle 1 #2-3', 'Valentina@gmail.com');
INSERT INTO Personas (idPersona, nombre, apellidos, identificacion, tipoIdentificacion, dirrecion, correoElectronico)
VALUES (7, 'Diego', 'Gomez', '654654', 'C.C', 'Calle 2 #4-5', 'Diego@gmail.com');
INSERT INTO Personas (idPersona, nombre, apellidos, identificacion, tipoIdentificacion, dirrecion, correoElectronico)
VALUES (8, 'Julian', 'Valderrma', '464567', 'C.C', 'Calle 3 #6-7', 'Julian@gmail.com');
INSERT INTO Personas (idPersona, nombre, apellidos, identificacion, tipoIdentificacion, dirrecion, correoElectronico)
VALUES (9, 'Samuel', 'Cardenas', '4687678687', 'C.C', 'Calle 4 #8-9', 'Samuel@gmail.com');
INSERT INTO Personas (idPersona, nombre, apellidos, identificacion, tipoIdentificacion, dirrecion, correoElectronico)
VALUES (10, 'Antonio', 'Paez', '67867687687', 'C.C', 'Calle 5 #10-11', 'Antonio@gmail.com');
